name: Test Django App

on: [push]

jobs:
  build:
    name: Build and Test Django app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        env:
          DJANGO_SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          pytest -v
